### ISSUE TITLE
怎么使用swiper？

### ISSUE THREAD

**Issue by Kanchil** [tower1229/Flow-UI#4]

**Comment by tower1229** [comment]
幻灯片吗？可以用[这个](http://flow-ui.refined-x.com/docs.html#Slide(%E5%B9%BB%E7%81%AF%E7%89%87))

**Comment by Kanchil** [comment]
需要使用到swiper，所以类似地像引入swiper这样的第三方插件有没有一套使用方案呢？

**Comment by tower1229** [comment]
三种情况，
一：如果插件本身支持CMD模块化规范可以直接丢进`modules/`，用`require('文件名')`来加载；
二：如果插件是未模块化的，可以手动为插件增加模块化包裹代码，然后丢进`modules/`；
三：如果插件既没有模块化，又不想手动添加模块化包裹，那就用[base.getScript()](http://flow-ui.refined-x.com/docs.html#Base(%E5%B7%A5%E5%85%B7%E5%8C%85))方法异步加载插件。

**Comment by Kanchil** [comment]
嗯！谢谢
