### ISSUE TITLE
ie浏览器下cutdown,倒计时使用不了

### ISSUE THREAD

**Issue by Kanchil** [tower1229/Flow-UI#5]
项目要求兼容到ie8，炸！ie浏览器下cutdown倒计时插件使用不了。ie9下报错

**Comment by tower1229** [comment]
@Kanchil 能把控制台截图我看下吗，我这里测试的不报错

**Comment by Kanchil** [comment]
今天又打开，发现自己莫名的好了。没有报错。。。很神奇！昨天报的是不合法的Date，我百度说是ie下不支持new Date(参数)这种用法，会报不合法的日期 @tower1229

**Comment by tower1229** [comment]
嗯
