### ISSUE TITLE
若能整合一个hash的前端路由就完美了

### ISSUE THREAD

**Issue by hasbug** [tower1229/Flow-UI#6]
这个框架能够用director.js进行配合开发吗？

**Comment by tower1229** [comment]
@hasbug flow-ui只是UI层的框架，可以跟任何开发模式或底层框架结合使用，你可以类比成Bootstrap，只不过在UI自定义、模块化、自动化开发上flow-ui整合了自己的实现方案，抛开这些后其实就是一个UI框架。

SPA其实不是flow-ui的重点覆盖业务，flow-ui最大的优势在于定制性，更适合作为一个灵活的建站脚手架，基于flow-ui可以轻易的修改出任意UI风格。
